classdef AnalysisRegistry

    properties (Constant)
        FitCenter = struct("OutputVars", ["XCenter", "YCenter", "XWidth", "YWidth"], ...
                       "OutputData", [], ...
                       "FuncName", "fitCenter")
        FitGauss = struct("OutputVars", ["GaussX", "GaussY", "GaussXWid", "GaussYWid"], ...
                          "OutputData", [], ...
                          "FuncName", "fitGauss")
        FitPSF = struct("OutputVars", [], ... 
                        "OutputData", []) % "PSFImage"
        CalibLatR = struct("OutputVars", ["LatX", "LatY"], ... % ["LatX", "LatY"]
                           "OutputData", [], ...
                           "FuncName", "calibLatR")
        CalibDMD = struct("OutputVars", [], ... % ["DmdXC", "DmdYC"]
                          "OutputData", []) % "DmdV"
    end

end
