%% Re-calibrate the lattice to a new dataset
clear; clc; close all
% Set an initial calibration file location and new data location for re-calibration
p = LatCalibrator( ...
    "LatCalibFilePath", "calibration/LatCalib_20241118.mat", ... 
    "DataPath", "calibration/example_data/20241115_gray_cross_on_black_angled_angle=-17.1_width=5_row=0.mat");
    % "DataPath", "data/2024/11 November/20241115 projecting gray/gray_cross_on_black_angled_angle=-17.1_width=5_row=0.mat");

%%
p.recalibrate( ...
    "reset_centers", false, ...
    "calibO", true, "signal_index", 1, ...
    "sites", Lattice.prepareSite('hex', 'latr', 20), ...
    "plot_diagnosticV", false, ...
    "plot_diagnosticR", false, ...
    "plot_diagnosticO", true)

%% Save re-calibration result (default is with today's date)
close all
p.save()
