%% Re-calibrate the lattice to a new dataset
clear; clc; close all
% Set an initial calibration file location and new data location for re-calibration
p = LatCalibrator( ...
    "LatCalibFilePath", "calibration/LatCalib_20241028.mat", ... 
    "DataPath", "data/2024/11 November/20241104/gray_on_black_anchor=64_array64_spacing=70_asym_r=15_r=7.mat");

%%
p.recalibrate( ...
    "reset_centers", true, ...
    "calibO", true, "signal_index", 1, ...
    "sites", Lattice.prepareSite('hex', 'latr', 20), ...
    "plot_diagnosticV", false, ...
    "plot_diagnosticR", false, ...
    "plot_diagnosticO", true)

%% Save re-calibration result (default is with today's date)
close all
p.save()
